CREATE TABLE staging.employee_raw(
	row_num SERIAL,
	Age TEXT,
	Attrition TEXT,
	BusinessTravel TEXT,
	DailyRate TEXT,
	Department TEXT,
	DistanceFromHome TEXT,
	Education TEXT,
	EducationField TEXT,
	EmployeeCount TEXT,
	EmployeeNumber TEXT,
	EnvironmentSatisfaction TEXT,
	Gender TEXT,
	HourlyRate TEXT,
	JobInvolvement TEXT,
	JobLevel TEXT,
	JobRole TEXT,
	JobSatisfaction TEXT,
	MaritalStatus TEXT,
	MonthlyIncome TEXT,
	MonthlyRate TEXT,
	NumCompaniesWorked TEXT,
	Over18 TEXT,
	OverTime TEXT,
	PercentSalaryHike TEXT,
	PerformanceRating TEXT,
	RelationshipSatisfaction TEXT,
	StandardHours TEXT,
	StockOptionLevel TEXT,
	TotalWorkingYears TEXT,
	TrainingTimesLastYear TEXT,
	WorkLifeBalance TEXT,
	YearsAtCompany TEXT,
	YearsInCurrentRole TEXT,
	YearsSinceLastPromotion TEXT,
	YearsWithCurrManager TEXT
);


